Mostly-complete refactor of the code to support whitelist.json interi…
versatus/versatus-ansible pull request #10
Opened 2023-10-30 17:22 UTC by mattgeddes

…m quorum config

There are still some things that aren't as dynamic as or performant as they should be, but this is able to stand up alphanet as best we can tell, including generating and propogating the whitelist.json file across all nodes. This probably needs a bit of a rework in order to be usable by operators again.

2023-10-31 16:26 UTC, mikehostetler approved these changes

2024-01-29 20:18 UTC, mikehostetler requested changes

2024-01-29 20:18 UTC, mikehostetler commented on roles/versatus_compute_node/meta/main.yml
> +<<<<<<< Updated upstream
Flagging to resolve this merge

2024-01-29 20:18 UTC, mikehostetler commented on roles/versatus_storage_node/meta/main.yml
> +<<<<<<< Updated upstream
Flagging to resolve this merge

2024-01-31 07:34 UTC, eureka-cpu approved these changes

2024-01-31 09:52 UTC, merged